Update multi/vim/bundle/asyncomplete
Upgrade lsp/complete packages to fix disappearing letters when inserting
text in lua with new sumneko lsp. Seems better?

Changelog:
Switch to supported vlime repo (#250)
Add vlime (#248)
Fix error: "E118: Too many arguments for function: copy" (#249)