Add glsl to love tags
Also note why I'm not using the python version (a question I ask my
self every time). Maybe it doesn't work because I'm under WSL, but I
installed fswatch in apt. I get this error:
    AttributeError: python3: undefined symbol: fsw_init_library